- hosts: localhost
  gather_facts: False
  roles:
    - generate-zuul-manifest
    - fetch-output
    - role: upload-logs
      vars:
        zuul_log_url: "http://localhost:8000"
        zuul_log_verbose: true
