- hosts: localhost
  gather_facts: True 
  tasks:
    - command: ls -l
    - command: pwd
    - debug:
        msg: "ansible_user_dir/zuul-output: {{ ansible_user_dir }}/zuul-output"
    - debug:
        msg: "ansible_user_dir: {{ ansible_user_dir }}"
    - debug:
        msg: "zuul.project.src_dir: {{ zuul.project.src_dir }}"
