- hosts: all
  roles:
    - add-build-sshkey
    - prepare-workspace
    - ensure-pip
    - role: ensure-python
      vars:
        python_version: '3.10'
    - role: ensure-bazel
      vars:
        bazel_version: '6.3.1'
